/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 about.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/about.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[-153.707, -59.993, 306.082]} rotation={[0.146, -0.041, -0.274]} scale={0.857}>
          <mesh geometry={nodes.Cylinder_4.geometry} material={nodes.Cylinder_4.material} position={[-14.558, 41.512, 5.447]} rotation={[0.261, 0.023, 0.084]} />
          <mesh geometry={nodes.Cylinder_3.geometry} material={nodes.Cylinder_3.material} position={[0, 18.907, 0]} />
          <mesh geometry={nodes.Cylinder_2.geometry} material={nodes.Cylinder_2.material} position={[-0.393, -30.221, -1.028]} />
          <mesh geometry={nodes.Cylinder.geometry} material={nodes.Cylinder.material} position={[-0.393, -37.79, -1.028]} />
        </group>
        <group position={[368.859, -246.678, -203.913]} rotation={[-0.146, -0.439, -0.767]} scale={0.901}>
          <mesh geometry={nodes.Torus_8.geometry} material={nodes.Torus_8.material} rotation={[0, 0, -0.262]} />
          <mesh geometry={nodes.Torus_6.geometry} material={nodes.Torus_6.material} rotation={[0, 0, -1.833]} />
          <mesh geometry={nodes.Torus_4.geometry} material={nodes.Torus_4.material} rotation={[0, 0, 2.88]} />
          <mesh geometry={nodes.Torus_2.geometry} material={nodes.Torus_2.material} rotation={[0, 0, 1.309]} />
          <mesh geometry={nodes.Torus_7.geometry} material={nodes.Torus_7.material} rotation={[0, 0, -Math.PI / 3]} />
          <mesh geometry={nodes.Torus_5.geometry} material={nodes.Torus_5.material} rotation={[0, 0, -2.618]} />
          <mesh geometry={nodes.Torus_3.geometry} material={nodes.Torus_3.material} rotation={[0, 0, 2.094]} />
          <mesh geometry={nodes.Torus.geometry} material={nodes.Torus.material} rotation={[0, 0, Math.PI / 6]} />
        </group>
        <group position={[-422.26, 12.062, 41.738]} rotation={[0.692, 0.285, 0.493]} scale={0.84}>
          <mesh geometry={nodes.Cylinder_1.geometry} material={nodes.Cylinder_1.material} position={[0.64, -45.332, 0.71]} />
          <mesh geometry={nodes.Cube.geometry} material={nodes.Cube.material} position={[0, -13.667, 0]} />
        </group>
        <group position={[-275.5, -150.001, 329.713]} rotation={[-0.411, -0.215, -0.22]} scale={0.78}>
          <group position={[-57.889, -24.247, 0.479]}>
            <mesh geometry={nodes.mesh_19_instance_1.geometry} material={nodes.mesh_19_instance_1.material} />
            <mesh geometry={nodes.mesh_19_instance_2.geometry} material={nodes.mesh_19_instance_2.material} position={[10, 0, 0]} />
            <mesh geometry={nodes.mesh_19_instance_3.geometry} material={nodes.mesh_19_instance_3.material} position={[20, 0, 0]} />
            <mesh geometry={nodes.mesh_19_instance_4.geometry} material={nodes.mesh_19_instance_4.material} position={[30, 0, 0]} />
          </group>
          <mesh geometry={nodes.Rectangle_7.geometry} material={nodes.Rectangle_7.material} position={[-39.239, 0.912, 0.479]} />
          <mesh geometry={nodes.Rectangle_8.geometry} material={nodes.Rectangle_8.material} position={[-39.239, 10.75, 2.073]} rotation={[0, 0, -Math.PI / 2]} />
          <mesh geometry={nodes.Rectangle_6.geometry} material={nodes.Rectangle_6.material} position={[-39.239, 11.051, 0.479]} />
          <mesh geometry={nodes.Rectangle_5.geometry} material={nodes.Rectangle_5.material} position={[-39.239, 21.5, 0.479]} />
          <mesh geometry={nodes.Rectangle_4.geometry} material={nodes.Rectangle_4.material} position={[-57.889, -24.247, 0.479]} />
          <mesh geometry={nodes.Rectangle_3.geometry} material={nodes.Rectangle_3.material} position={[-32.79, -36.18, 0.479]} />
          <mesh geometry={nodes.Ellipse_2.geometry} material={nodes.Ellipse_2.material} position={[47.393, -27.436, 0.486]} />
          <mesh geometry={nodes.Ellipse.geometry} material={nodes.Ellipse.material} position={[27.75, -27.436, 0.486]} />
          <mesh geometry={nodes.Rectangle_2.geometry} material={nodes.Rectangle_2.material} position={[0, 0, -6.073]} />
        </group>
        <group position={[-381.156, 221.257, -331.516]} rotation={[-0.086, -0.127, 0.442]} scale={[1.927, 1.849, 1.899]}>
          <mesh geometry={nodes.Cylinder_2_1.geometry} material={nodes.Cylinder_2_1.material} position={[0.709, 35.733, 40.727]} rotation={[1.924, 0, 0]} />
          <mesh geometry={nodes.Star.geometry} material={nodes.Star.material} position={[0.599, 36.024, 37.546]} rotation={[0.353, 0, 0]} />
          <mesh geometry={nodes.Cylinder_5.geometry} material={nodes.Cylinder_5.material} position={[-0.189, -68.822, 0.199]} rotation={[Math.PI, 0, 0]} />
          <mesh geometry={nodes.Cube_3.geometry} material={nodes.Cube_3.material} position={[-59.183, 25.535, -1.283]} rotation={[0, 0, Math.PI / 6]} scale={[-1, 1, 1]} />
          <mesh geometry={nodes.Cube_2.geometry} material={nodes.Cube_2.material} position={[59.183, 26.262, -1.283]} rotation={[0, 0, -Math.PI / 6]} />
          <mesh geometry={nodes.Cube_1.geometry} material={nodes.Cube_1.material} position={[-0.21, 34.233, 0]} />
        </group>
        <group position={[-32.072, -190.972, -54.631]} rotation={[-0.106, 0.381, 0.28]} scale={0.964}>
          <group position={[-3.716, 0, -16.395]} rotation={[0.087, 0, -Math.PI / 9]}>
            <mesh geometry={nodes['%'].geometry} material={nodes['%'].material} position={[-27.198, -43.343, 1.563]} />
            <mesh geometry={nodes['%_1'].geometry} material={nodes['%_1'].material} position={[-27.198, -43.343, 1.563]} />
            <mesh geometry={nodes['%_2'].geometry} material={nodes['%_2'].material} position={[-27.198, -43.343, 1.563]} />
            <mesh geometry={nodes.Shape.geometry} material={nodes.Shape.material} position={[-41.286, -75.022, -5.563]} />
          </group>
          <group position={[20.388, -1.29, 10.577]} rotation={[-0.174, -0.023, 0.084]}>
            <mesh geometry={nodes.Ellipse_2_2.geometry} material={nodes.Ellipse_2_2.material} position={[0.864, 58.75, 3.106]} />
            <mesh geometry={nodes.Ellipse_6.geometry} material={nodes.Ellipse_6.material} position={[0.864, 58.75, 2.587]} />
            <mesh geometry={nodes['%_3'].geometry} material={nodes['%_3'].material} position={[-27.198, -43.343, 1.563]} />
            <mesh geometry={nodes['%_4'].geometry} material={nodes['%_4'].material} position={[-27.198, -43.343, 1.563]} />
            <mesh geometry={nodes['%_5'].geometry} material={nodes['%_5'].material} position={[-27.198, -43.343, 1.563]} />
            <mesh geometry={nodes.Shape_1.geometry} material={nodes.Shape_1.material} position={[-41.286, -75.022, -5.563]} />
          </group>
        </group>
        <group position={[-21.706, 134.65, 120.373]} rotation={[-0.553, 0.738, -0.828]} scale={2.423}>
          <mesh geometry={nodes.Cube_4.geometry} material={nodes.Cube_4.material} position={[38.239, 1.889, -54.328]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} />
          <mesh geometry={nodes.Cylinder_6.geometry} material={nodes.Cylinder_6.material} position={[0.685, 1.653, -56.203]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Cylinder_2_2.geometry} material={nodes.Cylinder_2_2.material} position={[-1.188, -3.225, 15.591]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Torus_1.geometry} material={nodes.Torus_1.material} position={[0, 0, 37.58]} scale={0.73} />
          <mesh geometry={nodes.Cylinder_7.geometry} material={nodes.Cylinder_7.material} position={[0.201, -0.906, -35.389]} rotation={[Math.PI / 2, 0, 0]} scale={0.73} />
        </group>
        <group position={[354.927, 276.527, 26.82]} rotation={[0.106, -0.043, -0.389]} scale={1.096}>
          <group position={[0.005, -18.081, 1.54]}>
            <mesh geometry={nodes.mesh_47_instance_1.geometry} material={nodes.mesh_47_instance_1.material} position={[0, 40, 0]} />
            <mesh geometry={nodes.mesh_47_instance_2.geometry} material={nodes.mesh_47_instance_2.material} position={[20, 34.641, 0]} rotation={[0, 0, -Math.PI / 6]} />
            <mesh geometry={nodes.mesh_47_instance_3.geometry} material={nodes.mesh_47_instance_3.material} position={[34.641, 20, 0]} rotation={[0, 0, -Math.PI / 3]} />
            <mesh geometry={nodes.mesh_47_instance_4.geometry} material={nodes.mesh_47_instance_4.material} position={[40, 0, 0]} rotation={[0, 0, -Math.PI / 2]} />
            <mesh geometry={nodes.mesh_47_instance_5.geometry} material={nodes.mesh_47_instance_5.material} position={[34.641, -20, 0]} rotation={[0, 0, -2.094]} />
            <mesh geometry={nodes.mesh_47_instance_6.geometry} material={nodes.mesh_47_instance_6.material} position={[20, -34.641, 0]} rotation={[0, 0, -2.618]} />
            <mesh geometry={nodes.mesh_47_instance_7.geometry} material={nodes.mesh_47_instance_7.material} position={[0, -40, 0]} rotation={[0, 0, -Math.PI]} />
            <mesh geometry={nodes.mesh_47_instance_8.geometry} material={nodes.mesh_47_instance_8.material} position={[-20, -34.641, 0]} rotation={[0, 0, 2.618]} />
            <mesh geometry={nodes.mesh_47_instance_9.geometry} material={nodes.mesh_47_instance_9.material} position={[-34.641, -20, 0]} rotation={[0, 0, 2.094]} />
            <mesh geometry={nodes.mesh_47_instance_10.geometry} material={nodes.mesh_47_instance_10.material} position={[-40, 0, 0]} rotation={[0, 0, Math.PI / 2]} />
            <mesh geometry={nodes.mesh_47_instance_11.geometry} material={nodes.mesh_47_instance_11.material} position={[-34.641, 20, 0]} rotation={[0, 0, Math.PI / 3]} />
            <mesh geometry={nodes.mesh_47_instance_12.geometry} material={nodes.mesh_47_instance_12.material} position={[-20, 34.641, 0]} rotation={[0, 0, Math.PI / 6]} />
          </group>
          <group position={[0.265, -17.692, 0.103]}>
            <mesh geometry={nodes.mesh_48_instance_1.geometry} material={nodes.mesh_48_instance_1.material} position={[0, 40, 0]} />
            <mesh geometry={nodes.mesh_48_instance_2.geometry} material={nodes.mesh_48_instance_2.material} position={[40, 0, 0]} rotation={[0, 0, -Math.PI / 2]} />
            <mesh geometry={nodes.mesh_48_instance_3.geometry} material={nodes.mesh_48_instance_3.material} position={[0, -40, 0]} rotation={[0, 0, -Math.PI]} />
            <mesh geometry={nodes.mesh_48_instance_4.geometry} material={nodes.mesh_48_instance_4.material} position={[-40, 0, 0]} rotation={[0, 0, Math.PI / 2]} />
          </group>
          <mesh geometry={nodes.Cube_2_1.geometry} material={nodes.Cube_2_1.material} position={[-3.293, -21.94, 9.43]} rotation={[-0.004, 0.002, 2.618]} />
          <mesh geometry={nodes.Cube_5.geometry} material={nodes.Cube_5.material} position={[3.544, -10.06, 9.43]} rotation={[0, 0, -Math.PI / 6]} />
          <mesh geometry={nodes.Rectangle_3_1.geometry} material={nodes.Rectangle_3_1.material} position={[0.005, -18.081, 1.54]} />
          <mesh geometry={nodes.Rectangle_2_1.geometry} material={nodes.Rectangle_2_1.material} position={[0.265, -17.692, 0.103]} />
          <mesh geometry={nodes.Cylinder_3_1.geometry} material={nodes.Cylinder_3_1.material} position={[-0.155, 43.325, 0.605]} />
          <mesh geometry={nodes.Cylinder_2_3.geometry} material={nodes.Cylinder_2_3.material} position={[-0.155, 49.042, 0.605]} />
          <mesh geometry={nodes.Torus_9.geometry} material={nodes.Torus_9.material} position={[-0.178, 67.16, 0.528]} />
          <mesh geometry={nodes.Cylinder_8.geometry} material={nodes.Cylinder_8.material} position={[0, -19.636, -4.772]} rotation={[Math.PI / 2, 0, 0]} scale={2.408} />
        </group>
        <group position={[434.165, -72.626, 131.85]} rotation={[-Math.PI / 4, 0.193, 0]} scale={0.848}>
          <group position={[-34.132, -13.445, -3.376]}>
            <mesh geometry={nodes.mesh_56_instance_1.geometry} material={nodes.mesh_56_instance_1.material} />
            <mesh geometry={nodes.mesh_56_instance_2.geometry} material={nodes.mesh_56_instance_2.material} position={[24.2, 0, 0]} />
            <mesh geometry={nodes.mesh_56_instance_3.geometry} material={nodes.mesh_56_instance_3.material} position={[48.4, 0, 0]} />
            <mesh geometry={nodes.mesh_56_instance_4.geometry} material={nodes.mesh_56_instance_4.material} position={[72.6, 0, 0]} />
          </group>
          <group position={[-34.132, -38.073, -3.376]}>
            <mesh geometry={nodes.mesh_57_instance_1.geometry} material={nodes.mesh_57_instance_1.material} />
            <mesh geometry={nodes.mesh_57_instance_2.geometry} material={nodes.mesh_57_instance_2.material} position={[24.2, 0, 0]} />
            <mesh geometry={nodes.mesh_57_instance_3.geometry} material={nodes.mesh_57_instance_3.material} position={[48.4, 0, 0]} />
            <mesh geometry={nodes.mesh_57_instance_4.geometry} material={nodes.mesh_57_instance_4.material} position={[72.6, 0, 0]} />
          </group>
          <group position={[-34.132, -63.961, -3.376]}>
            <mesh geometry={nodes.mesh_58_instance_1.geometry} material={nodes.mesh_58_instance_1.material} />
            <mesh geometry={nodes.mesh_58_instance_2.geometry} material={nodes.mesh_58_instance_2.material} position={[24.2, 0, 0]} />
            <mesh geometry={nodes.mesh_58_instance_3.geometry} material={nodes.mesh_58_instance_3.material} position={[48.4, 0, 0]} />
            <mesh geometry={nodes.mesh_58_instance_4.geometry} material={nodes.mesh_58_instance_4.material} position={[72.6, 0, 0]} />
          </group>
          <mesh geometry={nodes.Rectangle_7_1.geometry} material={nodes.Rectangle_7_1.material} position={[-22.816, 11.699, -3.376]} />
          <mesh geometry={nodes.Rectangle_8_1.geometry} material={nodes.Rectangle_8_1.material} position={[38.836, 11.699, -3.376]} />
          <mesh geometry={nodes.Rectangle_6_1.geometry} material={nodes.Rectangle_6_1.material} position={[14.508, 11.699, -3.376]} />
          <mesh geometry={nodes.Rectangle_5_1.geometry} material={nodes.Rectangle_5_1.material} position={[-34.132, -13.445, -3.376]} />
          <mesh geometry={nodes.Rectangle_4_1.geometry} material={nodes.Rectangle_4_1.material} position={[-34.132, -38.073, -3.376]} />
          <mesh geometry={nodes.Rectangle_3_2.geometry} material={nodes.Rectangle_3_2.material} position={[-34.132, -63.961, -3.376]} />
          <mesh geometry={nodes.Rectangle_2_2.geometry} material={nodes.Rectangle_2_2.material} position={[-0.468, 53.943, 8.312]} rotation={[0.698, 0, 0]} scale={[1, 0.852, 1]} />
          <mesh geometry={nodes.Cube_6.geometry} material={nodes.Cube_6.material} position={[0, -26.244, -15.034]} />
        </group>
        <group position={[-171.728, 408.832, -94.503]} rotation={[0.65, 0, 0.342]} scale={0.817}>
          <mesh geometry={nodes.Rectangle_4_2.geometry} material={nodes.Rectangle_4_2.material} position={[7.43, 7, -5.778]} rotation={[0.262, 0, 0]} />
          <mesh geometry={nodes.Rectangle_3_3.geometry} material={nodes.Rectangle_3_3.material} position={[-0.488, 19.27, -11.595]} rotation={[0.175, 0, 0]} />
          <mesh geometry={nodes.Rectangle_2_3.geometry} material={nodes.Rectangle_2_3.material} position={[4.02, 21.125, -19.934]} rotation={[0.087, 0, 0]} />
          <mesh geometry={nodes.Cube_7.geometry} material={nodes.Cube_7.material} position={[-0.93, -3.883, -29.724]} />
        </group>
        <group position={[226.503, -92.646, -248.417]} rotation={[-0.152, -0.571, 0.333]} scale={1.208}>
          <mesh geometry={nodes.Rectangle_2_4.geometry} material={nodes.Rectangle_2_4.material} position={[3.403, 20.39, 24.575]} />
          <mesh geometry={nodes.Cylinder_2_4.geometry} material={nodes.Cylinder_2_4.material} position={[62.727, 56.828, 7.856]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Cylinder_9.geometry} material={nodes.Cylinder_9.material} position={[-59.245, 56.828, 7.856]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Ellipse_8.geometry} material={nodes.Ellipse_8.material} position={[64.767, 29.28, 28.536]} rotation={[0, 0, Math.PI / 2]} />
          <mesh geometry={nodes.Ellipse_8_1.geometry} material={nodes.Ellipse_8_1.material} position={[38.451, 29.28, 28.536]} rotation={[0, 0, Math.PI / 2]} />
          <mesh geometry={nodes.Ellipse_7.geometry} material={nodes.Ellipse_7.material} position={[51.914, 16.122, 28.536]} />
          <mesh geometry={nodes.Ellipse_4.geometry} material={nodes.Ellipse_4.material} position={[51.914, 42.438, 28.536]} />
          <mesh geometry={nodes.Rectangle_4_3.geometry} material={nodes.Rectangle_4_3.material} position={[-36.568, 29.282, 28.536]} rotation={[0, 0, Math.PI / 2]} />
          <mesh geometry={nodes.Rectangle_4_4.geometry} material={nodes.Rectangle_4_4.material} position={[-61.36, 29.282, 28.536]} rotation={[0, 0, Math.PI / 2]} />
          <mesh geometry={nodes.Rectangle_3_4.geometry} material={nodes.Rectangle_3_4.material} position={[-48.964, 16.886, 28.536]} />
          <mesh geometry={nodes.Rectangle_2_5.geometry} material={nodes.Rectangle_2_5.material} position={[-48.964, 41.678, 28.536]} />
          <mesh geometry={nodes.Ellipse_3.geometry} material={nodes.Ellipse_3.material} position={[51.609, 28.678, 27.456]} />
          <mesh geometry={nodes.Ellipse_2_1.geometry} material={nodes.Ellipse_2_1.material} position={[-48.932, 28.678, 27.456]} />
          <mesh geometry={nodes.Ellipse_3_1.geometry} material={nodes.Ellipse_3_1.material} position={[51.609, 28.678, 26.381]} />
          <mesh geometry={nodes.Ellipse_1.geometry} material={nodes.Ellipse_1.material} position={[-48.932, 28.678, 26.381]} />
          <mesh geometry={nodes.Cube_8.geometry} material={nodes.Cube_8.material} position={[-0.019, 26.935, -4.206]} />
        </group>
        <group position={[477.859, 102.227, -386.445]} rotation={[0.054, 0.26, -0.171]} scale={1.104}>
          <mesh geometry={nodes.Torus_10.geometry} material={nodes.Torus_10.material} position={[-0.063, 61.044, -4.111]} />
          <mesh geometry={nodes.Sphere.geometry} material={nodes.Sphere.material} position={[0.506, -55.049, 1.477]} scale={1.224} />
          <mesh geometry={nodes.Cube_9.geometry} material={nodes.Cube_9.material} position={[0, 3.395, 0]} />
        </group>
        <group position={[189.3, 346.836, 53.877]} rotation={[0.446, 0.24, 0.328]} scale={0.825}>
          <mesh geometry={nodes.Rectangle_3_5.geometry} material={nodes.Rectangle_3_5.material} position={[-0.943, -8.885, -21.999]} rotation={[Math.PI, 0, 0]} />
          <mesh geometry={nodes.Rectangle_2_6.geometry} material={nodes.Rectangle_2_6.material} position={[48.373, 20.391, 12.125]} />
          <mesh geometry={nodes.Ellipse_5.geometry} material={nodes.Ellipse_5.material} position={[1.5, -9.742, 26.546]} />
          <mesh geometry={nodes.Cube_10.geometry} material={nodes.Cube_10.material} position={[0, -8.742, -7.589]} />
        </group>
        <directionalLight intensity={0.7} decay={2} rotation={[-0.579, 0.687, 0.801]} />
        <PerspectiveCamera makeDefault={false} far={100000} near={5} fov={45} position={[-67.632, 65.673, 3418.674]} rotation={[-0.01, -0.023, 0]} />
        <mesh geometry={nodes.Backdrop.geometry} material={nodes.Backdrop.material} position={[-74.5, 652.5, 2514.197]} />
      </group>
    </group>
  )
}

useGLTF.preload('/about.gltf')
