/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: famousandfaded (https://sketchfab.com/famousandfaded)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/airports-around-the-world-e58f56a352b540469fd209abf0c37bc5
Title: Airports around the world
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.167}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.matairport_material} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.matairport_material} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.matsurface_material} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
